  variables:
    DOCKER_REGISTRY: registry.gitlab.com
    DUMP_TEST_LOGS_TO_STDOUT: "true"


  before_script:
    - export PATH=${CI_PROJECT_DIR}:${PATH}
    - echo "DOCKER_REGISTRY_TRUSTED_ENVIRONMENT=${DOCKER_REGISTRY_TRUSTED_ENVIRONMENT}"
    - git submodule sync polaris-build
    - git submodule update --init --remote polaris-build

  stages:
    - build
    - test


  build-package-image:
    stage: build
    tags:
      - polaris-runner
    script:
        # for yarn builds we only build the base image (which also builds the src image that can be used to run tests)
        - package build-base-image


  test:
    stage: test
    tags:
      - polaris-runner
    script:
        # this runs the tests against the src image.
        - package test-package



    
