module.exports = {
  content: ["./src/**/*.{ts,tsx,jsx,js}"],
  prefix: "tw-",
  theme: {
    spacing: {
      px: '1px',
      0: '0px',
      1: "0.25rem",
      2: "0.5rem",
      3: "0.75rem",
      4: "1rem",
      5: "1.25rem",
      6: "1.5rem",
      7: "1.75rem",
      8: "2rem",
      9: '2.25rem',
      10: '2.5rem',
      11: '2.75rem',
      12: '3rem',
      14: '3.5rem',
      16: '4rem',
      20: '5rem',
      24: '6rem',
      28: '7rem',
      32: '8rem',
      36: '9rem',
      40: '10rem',
    },
    colors: ({colors}) => ({
      transparent: colors.transparent,
      black: colors.black,
      white: colors.white,
      chart: "#f2f3f6",
      ghostwhite: "ghostwhite",
      gray: {
        100: colors.gray["100"],
        200: colors.gray["300"],
        300: colors.gray["500"],
      },
      blue: {
        100: colors.sky["300"],
        200: colors.sky["500"],
        300: colors.sky["900"],
      }
    }),
    fontSize: {
      "vh": ["1vh", {lineHeight: "0.5rem"}],
      "2xs": ["0.625rem", {lineHeight: "0.75rem"}],
      xs: ['var(--xs)', { lineHeight: 'var(--xsline)' }],
      sm: ['var(--sm)', { lineHeight: 'var(--smline)' }],
      base: ['var(--base)', { lineHeight: 'var(--baseline)' }],
      lg: ['var(--lg)', { lineHeight: 'var(--lgline)' }],
      xl: ['var(--xl)', { lineHeight: 'var(--xlline)' }],
      "2xl": ['var(--2xl)', { lineHeight: 'var(--2xline)' }],
      "3xl": ['var(--3xl)', { lineHeight: 'var(--3xline)' }],
      '4xl': ['var(--4xl)', { lineHeight: 'var(--4xline)' }],
      '5xl': ['var(--5xl)', { lineHeight: 'var(--5xline)' }],
    },
    fontWeight: {
      light: "300",
      normal: "400",
      medium: "500",
      semibold: "600",
    },
    extend: {},
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [],
};
