export const actionTypes = {
  UPDATE_FLOW_METRICS: "UPDATE_FLOW_METRICS",
  UPDATE_WIP_INSPECTOR: "UPDATE_WIP_INSPECTOR",
  UPDATE_DEFAULTS: "UPDATE_DEFAULTS",
  RESET_MEASUREMENT_SETTINGS: "RESET_MEASUREMENT_SETTINGS",
  MUTATION_SUCCESS: "MUTATION_SUCCESS",
  MUTATION_FAILURE: "MUTATION_FAILURE",
  CLOSE_SUCCESS_MODAL: "CLOSE_SUCCESS_MODAL",
};

export const releaseActionTypes = {
  UPDATE_RELEASE_SETTING: "UPDATE_RELEASE_SETTING",
  UPDATE_DEFAULTS: "UPDATE_DEFAULTS",
  RESET_RELEASE_SETTING: "RESET_RELEASE_SETTING",
  MUTATION_SUCCESS: "MUTATION_SUCCESS",
  MUTATION_FAILURE: "MUTATION_FAILURE",
  CLOSE_SUCCESS_MODAL: "CLOSE_SUCCESS_MODAL",
}

export const mode = {
  INIT: "INIT",
  EDITING: "EDITING",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
};
