export const actionTypes = {
  UPDATE_WIP_PERIOD: "UPDATE_WIP_PERIOD",
  UPDATE_FLOW_PERIOD: "UPDATE_FLOW_PERIOD",
  UPDATE_TRENDS_PERIOD: "UPDATE_TRENDS_PERIOD",
  RESET_SLIDERS: "RESET_SLIDERS",
  MUTATION_SUCCESS: "MUTATION_SUCCESS",
  MUTATION_FAILURE: "MUTATION_FAILURE",
  UPDATE_DEFAULTS: "UPDATE_DEFAULTS",
  CLOSE_SUCCESS_MODAL: "CLOSE_SUCCESS_MODAL",
  CLOSE_ALERT_MODAL: "CLOSE_ALERT_MODAL",
  UPDATE_NAME: "UPDATE_NAME",
};

export const mode = {
  INIT: "INIT",
  EDITING: "EDITING",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  ALERT: "ALERT"
};
