export const actionTypes = {
  UPDATE_WIP_PERIOD: "UPDATE_WIP_PERIOD",
  UPDATE_FLOW_PERIOD: "UPDATE_FLOW_PERIOD",
  UPDATE_TRENDS_PERIOD: "UPDATE_TRENDS_PERIOD",
  RESET_SLIDERS: "RESET_SLIDERS",
  MUTATION_SUCCESS: "MUTATION_SUCCESS",
  UPDATE_DEFAULTS: "UPDATE_DEFAULTS",
  CLOSE_SUCCESS_MODAL: "CLOSE_SUCCESS_MODAL",
};

export const mode = {
  INIT: "INIT",
  EDITING: "EDITING",
  SUCCESS: "SUCCESS",
};
