export const actionTypes = {
  UPDATE_DAYS: "UPDATE_DAYS",
  UPDATE_CURRENT_STEP: "UPDATE_CURRENT_STEP",
  UPDATE_SELECTED_RECORDS: "UPDATE_SELECTED_RECORDS",
  NAVIGATE_AFTER_SUCCESS: "NAVIGATE_AFTER_SUCCESS",
  UPDATE_ERROR_MESSAGE: "UPDATE_ERROR_MESSAGE",
  UPDATE_SUCCESS_MESSAGE: "UPDATE_SUCCESS_MESSAGE",
  UPDATE_LOCAL_RECORDS: "UPDATE_LOCAL_RECORDS",
  UPDATE_TIMEOUT_EXECUTING: "UPDATE_TIMEOUT_EXECUTING",
};
