export const actionTypes = {
  UPDATE_METRIC: "UPDATE_METRIC",
  UPDATE_TARGET: "UPDATE_TARGET",
  UPDATE_CONFIDENCE: "UPDATE_CONFIDENCE",
  RESET_SLIDERS: "RESET_SLIDERS",
  MUTATION_SUCCESS: "MUTATION_SUCCESS",
  MUTATION_FAILURE: "MUTATION_FAILURE",
  UPDATE_DEFAULTS: "UPDATE_DEFAULTS",
  CLOSE_SUCCESS_MODAL: "CLOSE_SUCCESS_MODAL",
};

export const METRICS = {
  LEAD_TIME: "leadTime",
  CYCLE_TIME: "cycleTime",
};

export const mode = {
  INIT: "INIT",
  EDITING: "EDITING",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
};
