export const actionTypes = {
  UPDATE_DAYS: "UPDATE_DAYS",
  UPDATE_CURRENT_STEP: "UPDATE_CURRENT_STEP",
  UPDATE_SELECTED_RECORDS: "UPDATE_SELECTED_RECORDS",
  UPDATE_PARENT_CONTRIBUTOR_KEY: "UPDATE_PARENT_CONTRIBUTOR_KEY",
  NAVIGATE_AFTER_SUCCESS: "NAVIGATE_AFTER_SUCCESS",
  UPDATE_EXCLUDE_FROM_ANALYSIS: "UPDATE_EXCLUDE_FROM_ANALYSIS",
  UPDATE_PARENT_CONTRIBUTOR_NAME: "UPDATE_PARENT_CONTRIBUTOR_NAME",
  UPDATE_LOCAL_RECORDS: "UPDATE_LOCAL_RECORDS",
  UPDATE_ERROR_MESSAGE: "UPDATE_ERROR_MESSAGE",
  UPDATE_SUCCESS_MESSAGE: "UPDATE_SUCCESS_MESSAGE",
  UPDATE_TIMEOUT_EXECUTING: "UPDATE_TIMEOUT_EXECUTING",
  UPDATE_UNLINK_ALIASES: "UPDATE_UNLINK_ALIASES",
};
