export const actionTypes = {
    UPDATE_DAYS: "UPDATE_DAYS",
    UPDATE_CURRENT_STEP: "UPDATE_CURRENT_STEP",
    UPDATE_SELECTED_RECORDS: "UPDATE_SELECTED_RECORDS",
    UPDATE_PARENT_CONTRIBUTOR_KEY: "UPDATE_PARENT_CONTRIBUTOR_KEY",
    NAVIGATE_AFTER_SUCCESS: "NAVIGATE_AFTER_SUCCESS",
  };
  